milvus-io/milvus-sdk-cpp

.gitignore, CMakeLists.txt
=> Setup initial project structure

.github/workflows/main.yaml
=> ci: add pipeline for build with ubuntu.

.gitignore, Makefile, cmake/BuildUtils.cmake, cmake/DefineOptions.cmake, cmake/FindClangTools.cmake, cmake/ThirdPartyPackages.cmake, scripts/build.sh, scripts/proto_gen.sh, src/CMakeLists.txt, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h, src/proto/common.proto, src/proto/milvus.proto, src/proto/schema.proto
=> Initialize project

.clang-format, .clang-tidy, .github/workflows/main.yaml, .gitignore, CMakeLists.txt, scripts/cpplint.py, scripts/install_deps.sh, scripts/lint_exclusions.txt, scripts/lintutils.py, scripts/run_clang_format.py, scripts/run_clang_tidy.py, scripts/run_cpplint.py, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h
=> ci: porting cpplint/clang-format/clang-tidy from milvus-io/milvus

.github/mergify.yml, .github/workflows/main.yaml
- Add tag ci-pass while Build & Test success.
Issue: #13
=> ci: add initial mergify configuration.

CMakeLists.txt, examples/simple/CMakeLists.txt, examples/simple/main.cpp, src/CMakeLists.txt, src/impl/MilvusClientImpl.cpp, src/impl/Status.cpp, src/include/MilvusClient.h, src/include/Status.h, src/include/param/BaseParam.h, src/include/types/CollectionSchema.h, src/include/types/DataType.h, src/include/types/FieldSchema.h
=> Add a CrateCollection api for first step

src/impl/MilvusClientImpl.cpp, src/impl/Status.cpp, src/include/Status.h, test/CMakeLists.txt, test/ut/TestStatus.cpp
=> Refactoring milvus::Status

cmake/ThirdPartyPackages.cmake, examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/MilvusClient.h, src/include/types/CollectionDesc.h, src/include/types/CollectionInfo.h, src/include/types/CollectionStat.h, src/include/types/ConnectParam.h, src/include/types/FieldSchema.h, src/include/types/TimeoutSetting.h, src/proto-gen/proto-gen.cmake
=> Prepare for rpc connection

examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/include/types/CollectionSchema.h, src/include/types/DataType.h, src/include/types/FieldSchema.h
=> Implement first api

examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/Status.cpp, src/include/Status.h, src/include/types/CollectionSchema.h, src/include/types/FieldSchema.h, src/include/types/TimeoutSetting.h, test/ut/TestStatus.cpp
=> Refine the code style

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h, src/include/types/CollectionStat.h, src/include/types/Constants.h, src/include/types/PartitionInfo.h, src/include/types/PartitionStat.h
=> Declare more interfaces and fix some typo

.clang-tidy, src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/include/Status.h, test/ut/TestStatus.cpp
=> Clang-tidy for naming

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, test/it/TestHasCollection.cpp, test/it/mocks/MilvusMockedService.h
- HasCollection API and positive tests.
- Add All mock methods for mock server.
- Extract common grpc call for MilvisConnection.
Issue: #14 #27
=> Add HasCollection API.

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, test/it/TestCreateParition.cpp, test/it/TestDropParition.cpp, test/it/TestHasPartition.cpp
=> Add interface for Create/Drop/Has partition

src/impl/MilvusClientImpl.cpp
=> Handle server side error

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/types/PartitionInfo.h, test/it/TestShowPartitions.cpp
=> Add ShowPartitions interface.

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/MilvusClient.h, src/include/types/IndexDesc.h, src/include/types/IndexState.h
=> Add alias interfaces and index interfaces

.github/mergify.yml, .github/workflows/main.yaml, cmake/ThirdPartyPackages.cmake, scripts/install_deps.sh, test/it/mocks/MilvusMockedServer.cpp
- support build/test from centos7
- using container as builder on github
Related Issue: #51
=> Support centos7 as builder

DEVELOPMENT.md
=> Add initial DEVELOPMENT.md guide

src/impl/MilvusConnection.h
=> Fix typo Proto <- Proro

.github/mergify.yml
- remove ci-pass when any build pipeline failed.
- automic add ci-pass if not source code changed or only .md changed.
Issue: #23
=> Refine mergify.yml

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/MilvusClient.h, src/include/Status.h, src/include/types/PartitionInfo.h, src/include/types/TimeoutSetting.h, test/it/TestLoadPartitions.cpp
=> Implementation of LoadPartitions interface

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h
=> Add flush() for internal use

.github/workflows/main.yaml, .gitignore, CMakeLists.txt, Makefile, scripts/coverage.sh, scripts/install_deps.sh
=> Add code coverage

src/impl/MilvusClientImpl.cpp, src/include/types/ProgressMonitor.h, test/it/TestLoadPartitions.cpp
- add progress report callback.
=> Refine implementation of LoadPartitions

DEVELOPMENT.md
=> Modify DEVELOPMENT.md

scripts/coverage.sh
- remove coverage folder failed locally when already exists.
=> Fix for coverage scripts

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, test/it/TestReleasePartitions.cpp
=> Implementation of ReleasePartitions

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h, src/include/types/FieldData.h, src/include/types/IDArray.h, test/ut/TestFieldData.cpp, test/ut/TestIDArray.cpp
=> Prepare for insert api

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/include/types/IndexDesc.h, test/it/TestCreateIndex.cpp
=> Add CreateIndex() method

cmake/FindClangTools.cmake, scripts/install_deps.sh, src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h
=> Refine lint jobs

src/impl/MilvusClientImpl.cpp
=> Fix lint error on master

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, test/it/TestInsert.cpp, test/it/TypeUtils.h
=> Implement of Insert interface.

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h, src/include/types/FieldData.h, src/include/types/QueryArguments.h, src/include/types/QueryResults.h, src/include/types/SearchArguments.h, src/include/types/SearchResults.h, test/ut/TestQueryArguments.cpp, test/ut/TestSearchArguments.cpp, test/ut/TestSearchResults.cpp
=> Prepare for search() and query()

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/include/MilvusClient.h, src/include/types/FieldData.h, src/include/types/QueryArguments.h, src/include/types/QueryResults.h, test/CMakeLists.txt, test/it/TestInsert.cpp, test/it/TestQuery.cpp, test/it/mocks/MilvusMockedServer.cpp, test/it/mocks/MilvusMockedTest.cpp
=> Implement Query interface

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/MilvusClient.h, src/proto/common.proto, src/proto/milvus.proto
=> Update proto files

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/MilvusClient.h, src/include/types/ProgressMonitor.h, test/it/TestFlush.cpp, test/it/TestLoadPartitions.cpp, test/it/mocks/MilvusMockedService.h
=> Implement Flush()

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h
- Split each interface to steps: validata(opt), pre, rpc, wait_for_status(opt), post(opt)
=> Refactory for client implementation.

scripts/install_deps.sh
=> Support Ubuntu 20.04

src/impl/MilvusClientImpl.cpp, test/it/TestAlias.cpp
=> Implement alias interfaces

.github/workflows/main.yaml, CMakeLists.txt, Makefile, cmake/DefineOptions.cmake, scripts/build.sh, test/CMakeLists.txt, test/st/MilvusDockerServer.cpp, test/st/MilvusDockerServer.h, test/st/MilvusServerTest.h, test/st/TestCollection.cpp
=> Add empty acceptance test

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/include/MilvusClient.h, src/include/types/SearchArguments.h, src/include/types/SearchResults.h, test/it/TestSearch.cpp, test/ut/TestSearchResults.cpp, test/ut/TestTypeUtils.cpp
=> Implement Search interface (partial)

examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/include/types/CollectionDesc.h, src/include/types/CollectionSchema.h, src/include/types/CompactionPlan.h, src/include/types/CompactionState.h, src/include/types/Constants.h, src/include/types/FieldSchema.h, test/it/TestCompact.cpp, test/it/TestDescribeCollection.cpp, test/ut/TestCompactionPlan.cpp, test/ut/TestCompactionState.cpp, test/ut/TestFieldSchema.cpp
=> Implement compact interfaces

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, test/it/TestDropCollection.cpp
=> Add dropcollection interface

DEVELOPMENT.md
=> Update guides for development

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, test/it/TestLoadCollection.cpp
=> Add LoadCollection instant loading interface

src/impl/MilvusClientImpl.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/include/types/CollectionSchema.h, src/include/types/SearchArguments.h, src/include/types/SearchResults.h, test/it/TestSearch.cpp, test/st/MilvusServerTest.h, test/st/TestSearch.cpp, test/ut/TestSearchArguments.cpp, test/ut/TestSearchResults.cpp, test/ut/TestTypeUtils.cpp
=> Refine Search interface

src/impl/MilvusClientImpl.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/include/types/MetricType.h, src/include/types/SearchArguments.h, test/it/TestSearch.cpp, test/ut/TestTypeUtils.cpp
=> Using MetricType from user input for Search

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/milvus/MilvusClient.h, src/include/milvus/types/CalcDistanceArguments.h, src/include/milvus/types/DataType.h, src/include/milvus/types/DistanceArray.h, test/it/TestCalcDistance.cpp, test/ut/TestCalcDistanceArguments.cpp
=> Implement CalcDistance interfaces

scripts/install_deps.sh
=> Fix codecov not working

.github/workflows/main.yaml, cmake/MilvusSdkPackagesLinux.cmake, examples/CMakeLists.txt, src/CMakeLists.txt
=> Build test for rpm package

examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/milvus/MilvusClient.h, src/include/milvus/types/Constants.h, src/include/milvus/types/DmlResults.h, src/include/milvus/types/QueryArguments.h, src/include/milvus/types/SearchArguments.h, src/proto/common.proto, test/it/TestCreateCollection.cpp, test/it/TestDelete.cpp, test/it/TestInsert.cpp, test/st/TestSearch.cpp, test/ut/TestSearchArguments.cpp, test/ut/TestSearchResults.cpp, test/ut/TestTypeUtils.cpp
=> Refine travel timestamp and guarantee timestamp for query/search

.clang-tidy, examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/milvus/MilvusClient.h, src/include/milvus/types/ProgressMonitor.h
=> Fix example bug

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/milvus/MilvusClient.h, src/include/milvus/types/PartitionStat.h, test/it/TestGetPartitionStatistics.cpp, test/ut/TestPartitionStat.cpp
=> Implement GetPartitionStatistics

scripts/build.sh
=> Refine scripts for get cpu count under macOS

src/impl/MilvusClientImpl.cpp, test/it/TestGetMetrics.cpp
=> Implememnt GetMetrics interface

test/st/MilvusDockerServer.cpp
=> Promote milvus 2.0.0 for system testing

src/impl/MilvusClientImpl.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, test/it/TestGetPersistentSegmentInfo.cpp, test/ut/TestTypeUtils.cpp
=> GetPersistentSegmentInfo interface

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, test/it/TestRelseaseCollection.cpp
=> Add release collection interface

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/milvus/types/CollectionStat.h, test/it/TestGetCollectionsStatistics.cpp
=> Add GetCollectionStatistics() interface

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/include/milvus/types/IndexDesc.h, test/it/TestDescribeIndex.cpp
=> Add DescribeIndex Interface

examples/simple/main.cpp, src/include/milvus/types/CollectionStat.h, test/it/TestGetCollectionsStatistics.cpp
=> Refine the example

test/it/TestCreateIndex.cpp
=> Add create index tests

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, test/it/TestDropIndex.cpp
=> Add drop index interface

test/ut/TestTypeUtils.cpp
=> Add unittest cases

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h
=> Some refinements for wait for status

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/include/milvus/types/IndexState.h, test/it/TestGetIndexBuildProgress.cpp
=> Add GetIndexBuildProgress interface

src/impl/TypeUtils.cpp
=> Some refinements for CreateProtoFieldData

src/impl/TypeUtils.cpp, src/include/milvus/types/FieldSchema.h, test/it/TestCreateIndex.cpp, test/it/TestDescribeIndex.cpp, test/it/TestSearch.cpp, test/ut/TestTypeUtils.cpp
=> Increase code coverage to 99%

src/include/milvus/MilvusClient.h, src/include/milvus/types/Constants.h, src/include/milvus/types/HybirdTimestamp.h, test/ut/TestHybirdTimestamp.cpp
=> Utils function for hybird timestamp

src/include/milvus/types/HybirdTimestamp.h
=> Fix u_int64_t to uint64_t

DEVELOPMENT.md
=> Update tested platform in development guide

.github/workflows/release.yaml, scripts/build.sh
- using tag with vx.y.z will trigger a release pipeline
=> Add release pipeline on tag push

src/CMakeLists.txt, src/impl/MilvusClientImpl.cpp, src/impl/types/SearchArguments.cpp, src/include/milvus/types/IndexDesc.h, src/include/milvus/types/SearchArguments.h, test/it/TestSearch.cpp, test/st/TestSearch.cpp
- fix search arguments
issues: #158 #159
=> Fix SearchArguments/CreateIndex

src/impl/MilvusClientImpl.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/impl/types/IndexDesc.cpp, src/impl/types/SearchArguments.cpp, src/include/milvus/Status.h, src/include/milvus/types/Constants.h, src/include/milvus/types/IndexDesc.h, src/include/milvus/types/IndexType.h, test/it/TestCreateIndex.cpp, test/it/TestDescribeIndex.cpp, test/st/TestSearch.cpp, test/ut/TestIndexDesc.cpp, test/ut/TestTypeUtils.cpp
=> Refine for CreateIndex interface

src/impl/MilvusClientImpl.cpp, src/impl/types/SearchArguments.cpp, src/include/milvus/types/SearchArguments.h, test/it/TestSearch.cpp, test/st/TestSearch.cpp, test/ut/TestSearchArguments.cpp
=> Refine for SerachArguments

src/impl/MilvusClientImpl.cpp, src/impl/types/CalcDistanceArguments.cpp, src/impl/types/CollectionDesc.cpp, src/impl/types/CollectionInfo.cpp, src/impl/types/IndexDesc.cpp, src/impl/types/SearchArguments.cpp, src/include/milvus/types/CalcDistanceArguments.h, src/include/milvus/types/CollectionDesc.h, src/include/milvus/types/CollectionInfo.h, src/include/milvus/types/IndexDesc.h, src/include/milvus/types/SearchArguments.h, test/ut/TestCollectionInfo.cpp
=> Some headers refinement

DEVELOPMENT.md, README.md
=> Refine README.md

src/impl/MilvusConnection.cpp
=> Fix memory leak in MilvusConnection

DEVELOPMENT.md
Signed-off-by: groot <yihua.mo@zilliz.com>
=> Update proto files for v2.1

CMakeLists.txt, src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/impl/types/ConnectParam.cpp, src/include/milvus/types/ConnectParam.h, test/it/TestConnection.cpp, test/ut/TestConnectParam.cpp
=> Bugfix, return error while connect to incorrect server.

src/impl/MilvusClientImpl.cpp, test/st/TestCollection.cpp
=> Bugfix for ShowCollections

src/impl/MilvusClientImpl.cpp, test/it/TestCreateIndex.cpp
=> Call flush() before CreateIndexRequest

src/impl/MilvusClientImpl.cpp, src/proto-gen/proto-gen.cmake, test/it/TestSearch.cpp
=> Promote proto to latest version.

test/st/MilvusDockerServer.cpp
=> Update system testing with milvus 2.1

src/impl/MilvusClientImpl.cpp, src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/impl/types/FieldData.cpp, src/impl/types/SearchArguments.cpp, src/include/milvus/types/FieldData.h, src/include/milvus/types/SearchArguments.h, test/it/TestCalcDistance.cpp, test/it/TestSearch.cpp, test/st/TestSearchWithBinaryVectors.cpp, test/ut/TestCalcDistanceArguments.cpp, test/ut/TestFieldData.cpp, test/ut/TestSearchArguments.cpp, test/ut/TestTypeUtils.cpp
=> Bugfix for binary vectors

test/st/MilvusDockerServer.cpp
=> Promote milvus 2.1.1

src/impl/TypeUtils.cpp, src/impl/TypeUtils.h, src/impl/types/FieldData.cpp, src/impl/types/FieldSchema.cpp, src/include/milvus/types/Constants.h, src/include/milvus/types/DataType.h, src/include/milvus/types/FieldData.h, src/include/milvus/types/FieldSchema.h, test/it/TestInsert.cpp, test/st/MilvusServerTest.h, test/st/TestCollection.cpp, test/st/TestSearch.cpp, test/ut/TestFieldData.cpp, test/ut/TestFieldSchema.cpp, test/ut/TestTypeUtils.cpp
=> Support VarChar type.

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/include/milvus/MilvusClient.h, test/it/TestLoadCollection.cpp, test/it/TestLoadPartitions.cpp
=> Support replica in load collection/partitions

test/st/MilvusDockerServer.cpp
=> Update proto and st with milvus 2.1.4

examples/simple/main.cpp, src/impl/MilvusClientImpl.cpp, src/include/milvus/types/IndexState.h, test/st/MilvusDockerServer.cpp, test/st/TestCollection.cpp, test/st/TestSearch.cpp
- st with milvus 2.2.1
- update proto to latest master
=> Adaptation for version 2.2.x.

codecov.yml
=> add codecov configurations

.github/workflows/main.yaml, cmake/ThirdPartyPackages.cmake, scripts/build.sh, scripts/install_deps.sh
=> ci refactoring

src/impl/MilvusClientImpl.cpp, src/impl/MilvusClientImpl.h, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/include/milvus/MilvusClient.h, test/it/TestSearch.cpp
=> add timeout parameter for Search/Query

src/impl/MilvusClientImpl.cpp, src/impl/MilvusConnection.cpp, src/impl/MilvusConnection.h, src/impl/types/ConnectParam.cpp, src/include/milvus/types/ConnectParam.h, test/it/TestConnection.cpp, test/st/MilvusServerTest.h, test/st/TestConnectWithUser.cpp
=> feat: support username with password

.github/workflows/main.yaml, CMakeLists.txt, Makefile, cmake/ThirdPartyPackages.cmake, examples/simple/main.cpp, scripts/build.sh, src/impl/TypeUtils.cpp, test/CMakeLists.txt, test/it/TestCompact.cpp, test/it/mocks/MilvusMockedService.h
=> ci: adaptation for windows

cmake/MilvusProtoGen.cmake
=> fix: always using compiled protoc
